[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb34181ee64db223201e4e18759884c68ca4e054"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "ccaacfca582a869a454c756f9babf6a3d871e2eacbab54d9bf2d5d573898fad7"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.0.6+0/qwtw.v2.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20b156a3ad0afc974b555c342fb225b7adf5082a"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "bf3d47d19db93593c953ef07b8f73b06e98661ee59b72314551a3153cfd6b099"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.0.6+0/qwtw.v2.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4faa8b786ab745da332b274c19ab73199e3b8cab"
os = "windows"

    [[qwtw.download]]
    sha256 = "1ba5f58a9563259e5e04089bb2e6396ed30af378bfa513382d97e109274e332d"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.0.6+0/qwtw.v2.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28093abba0aef61144382cecbc725ef3172c0522"
os = "windows"

    [[qwtw.download]]
    sha256 = "c1ef3abd35c79258d5a08a16c59d8cdeb3f96bd7127f84a887a9ed3d1d18a41f"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.0.6+0/qwtw.v2.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
