[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b67a8d0149c02102f58d2348b3214200200a4a2a"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "11a200861b325d1a73292ccdcc66ae33b61515c481e7d52c68fb6bd8dce35ddf"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.0.5+0/qwtw.v2.0.5.x86_64-linux-gnu-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dbadb8f4fcd2a0077f9d159a2a435b8a5addba6"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "82ab957827839c9a832de8b4ec24b60e5319243018723f06c0db2ba84d4d4b95"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.0.5+0/qwtw.v2.0.5.x86_64-linux-gnu-cxx11.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e641d64aed4353adbcbe71e9c0b1da9e0ed9ceca"
os = "windows"

    [[qwtw.download]]
    sha256 = "8ed1ce274e358ba9c67fb83bc3c150e9c55ca408c62e6cbca6f98cce11ac17ec"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.0.5+0/qwtw.v2.0.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd8e99f82be7b5b21ff8b662e60d325ac06f4b95"
os = "windows"

    [[qwtw.download]]
    sha256 = "3a56c89c58718ccf4673507169051c67ddb29bf237ea2a8ac4f81fe60ff080c1"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.0.5+0/qwtw.v2.0.5.x86_64-w64-mingw32-cxx11.tar.gz"
