[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9baef5c3a58c964ad4bcbfcfeadb26139c36097a"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "5799a726b050c8be8ac9e91421cd276ec8710b1f1877c9a46c04775abeb87a7d"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.8.0+0/qwtw.v2.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4441a670c4425e54fb9e6f73a01a4f12433f45d"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "71de187a05011b50d11abc327ebfd52c3914ea713c5b24b5fbf0305724d41304"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.8.0+0/qwtw.v2.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c284cea06d45a2035914e68d48b0a17aa764b4f"
os = "windows"

    [[qwtw.download]]
    sha256 = "e007fca98ead3a285581191c0482053c82ae99c6e9785a13dbb34e239619363c"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.8.0+0/qwtw.v2.8.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8d6618a4510e25a347d2c6ff2df18e0f2f04564"
os = "windows"

    [[qwtw.download]]
    sha256 = "e06d1d5486f9cc7139189118cda92fe3f623b64b02c480bc3e8b2c671dc09c71"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.8.0+0/qwtw.v2.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
