[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c98e55cdf3ce153e50b0438e2e5b31eabf70c906"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "5796aa3a839f09aae6e0e9c0497e19ff472e6bcababdb20a6aa30941416c8a2b"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.1.0+0/qwtw.v2.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b3dd99b463a37f198b294413a45a025f08674c2"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "d731d3164c459868f8177796e2ecade35eaa9d76293d48a250b1364c89382b61"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.1.0+0/qwtw.v2.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a638668af3c5dedab78899d211ea672ccc31c40e"
os = "windows"

    [[qwtw.download]]
    sha256 = "cf4e71bbfea1c77166452e865a8f3469519e362c37f045a87ad28887c7ff2c69"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.1.0+0/qwtw.v2.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e3d1a04c7a5dd58ef91b0766ef747a74f4ce105"
os = "windows"

    [[qwtw.download]]
    sha256 = "3e6fe1dc4719ac6c1192f388bb05b41dd004c15f7df86c7ad476a0f0a836a856"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.1.0+0/qwtw.v2.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
