[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cda375a0932b79ac15a1e8c8857a79dc77f7509"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "809e3364ce728461b0f12e6dc758995b740fc2f8592ec23001f8db61bf22d15b"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.3.0+0/qwtw.v2.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc480fce1722a9722fe311517fdb47248373e2a1"
libc = "glibc"
os = "linux"

    [[qwtw.download]]
    sha256 = "ede49928cbc09726553e03c772a616c2181d26872bd459dae86bbd15500c8f6f"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.3.0+0/qwtw.v2.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46b8942cd49f7d6697a77163bbc8d74ac0178c96"
os = "windows"

    [[qwtw.download]]
    sha256 = "df60abe2a1bda823d4b6a6032a2dd1fb724d460c941825ea3b9b1f4ab6222f4d"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.3.0+0/qwtw.v2.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[qwtw]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e10cbefa172fb7e0624d2e4e2aca2be27035838b"
os = "windows"

    [[qwtw.download]]
    sha256 = "3651f5810e67ded7ef36df1038152c4037d2eb77447f5de6570a768d67afa307"
    url = "https://github.com/JuliaBinaryWrappers/qwtw_jll.jl/releases/download/qwtw-v2.3.0+0/qwtw.v2.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
